# Generated by Django 5.2.4 on 2025-07-24 18:06

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('company_type', models.CharField(choices=[('ballet', 'Ballet Company'), ('modern', 'Modern Dance Company'), ('contemporary', 'Contemporary Dance Company'), ('folk', 'Folk Dance Company'), ('musical_theater', 'Musical Theater'), ('opera', 'Opera Company'), ('independent', 'Independent'), ('school', 'Dance School'), ('other', 'Other')], default='ballet', max_length=50)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g., 'VHS Tape #47 - Mixed 1980s Content'", max_length=255)),
                ('description', models.TextField(blank=True, help_text='What we know about this digitized content')),
                ('source_format', models.CharField(choices=[('vhs', 'VHS'), ('betamax', 'Betamax'), ('8mm', '8mm Film'), ('16mm', '16mm Film'), ('digital', 'Digital'), ('dvd', 'DVD'), ('mini_dv', 'Mini DV'), ('hi8', 'Hi8'), ('umatic', 'U-matic'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('source_condition', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('degraded', 'Degraded')], max_length=20)),
                ('source_location', models.CharField(blank=True, help_text='Where was this found/acquired?', max_length=255)),
                ('estimated_date_range', models.CharField(blank=True, help_text="e.g., '1987-1990' or 'Early 1980s'", max_length=100)),
                ('donor_contact', models.CharField(blank=True, max_length=255)),
                ('acquisition_notes', models.TextField(blank=True)),
                ('cloudflare_stream_id', models.CharField(max_length=255, unique=True)),
                ('cloudflare_playback_url', models.URLField()),
                ('cloudflare_thumbnail_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('recording_quality', models.CharField(blank=True, choices=[('4K', '4K'), ('HD', 'HD (1080p)'), ('SD', 'SD (720p)'), ('archival', 'Archival Quality'), ('poor', 'Poor Quality')], max_length=20)),
                ('digitization_notes', models.TextField(blank=True, help_text='Technical notes about the digitization process')),
                ('needs_review', models.BooleanField(default=True, help_text='Needs archivist review to identify content')),
                ('status', models.CharField(choices=[('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='uploading', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('birth_year', models.PositiveIntegerField(blank=True, null=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('rank', models.CharField(blank=True, help_text='e.g., Principal, Soloist, Corps de Ballet', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('current_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_members', to='archive.company')),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='artistic_director',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_companies', to='archive.person'),
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('year_created', models.PositiveIntegerField(blank=True, null=True)),
                ('style', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('acts', models.PositiveIntegerField(default=1)),
                ('approximate_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('choreographer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.person')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composed_pieces', to='archive.person')),
                ('librettist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='libretto_pieces', to='archive.person')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('venue_type', models.CharField(choices=[('theater', 'Theater'), ('opera_house', 'Opera House'), ('studio', 'Studio'), ('outdoor', 'Outdoor'), ('concert_hall', 'Concert Hall'), ('other', 'Other')], default='theater', max_length=50)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('name', 'city', 'country')},
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Giselle - Opening Night'", max_length=255)),
                ('date', models.DateField()),
                ('season', models.CharField(blank=True, help_text="e.g., '2023-24 Season'", max_length=100)),
                ('program_notes', models.TextField(blank=True)),
                ('is_premiere', models.BooleanField(default=False)),
                ('is_gala', models.BooleanField(default=False)),
                ('is_matinee', models.BooleanField(default=False)),
                ('performance_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='archive.company')),
                ('conductor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_performances', to='archive.person')),
                ('stage_director', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directed_performances', to='archive.person')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='archive.venue')),
            ],
            options={
                'ordering': ['-date', 'performance_time'],
                'unique_together': {('title', 'date', 'venue')},
            },
        ),
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_time_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('end_time_seconds', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('content_type', models.CharField(choices=[('performance', 'Performance'), ('rehearsal', 'Rehearsal'), ('class', 'Class/Training'), ('warmup', 'Warm-up'), ('backstage', 'Backstage'), ('interview', 'Interview'), ('curtain_call', 'Curtain Call'), ('intermission', 'Intermission'), ('unknown', 'Unknown/Unidentified')], default='unknown', max_length=50)),
                ('clip_roles', models.JSONField(blank=True, default=dict, help_text="{'person_id': 'role_name'} for this specific clip")),
                ('movement_tags', models.JSONField(blank=True, default=list)),
                ('act_scene', models.CharField(blank=True, help_text="e.g., 'Act I, Scene 2' or 'Variation III'", max_length=100)),
                ('music_section', models.CharField(blank=True, help_text="e.g., 'Entrance of the Wilis'", max_length=200)),
                ('technical_notes', models.TextField(blank=True)),
                ('costume_notes', models.TextField(blank=True)),
                ('music_notes', models.TextField(blank=True)),
                ('archival_notes', models.TextField(blank=True, help_text='Archivist notes about identification, context, etc.')),
                ('video_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor')], max_length=20)),
                ('audio_quality', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor'), ('very_poor', 'Very Poor'), ('no_audio', 'No Audio')], max_length=20)),
                ('camera_angle', models.CharField(blank=True, help_text="e.g., 'Stage Left', 'Audience POV'", max_length=100)),
                ('identification_confidence', models.CharField(choices=[('certain', 'Certain'), ('probable', 'Probable'), ('possible', 'Possible'), ('uncertain', 'Uncertain')], default='uncertain', help_text='How confident are we in the identification?', max_length=20)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(blank=True, help_text='Which archivist verified this identification?', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('performance', models.ForeignKey(blank=True, help_text='Which specific performance is this clip from? Leave blank for rehearsals, classes, etc.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clips', to='archive.performance')),
                ('performers', models.ManyToManyField(blank=True, related_name='clips', to='archive.person')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.piece')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='archive.video')),
            ],
            options={
                'ordering': ['video', 'start_time_seconds'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(help_text="e.g., 'Giselle', 'Albrecht', 'Queen of the Wilis'", max_length=255)),
                ('is_principal', models.BooleanField(default=False)),
                ('is_understudy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast', to='archive.performance')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performances', to='archive.person')),
                ('piece', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_entries', to='archive.piece')),
            ],
            options={
                'ordering': ['performance', '-is_principal', 'role'],
                'unique_together': {('performance', 'person', 'piece', 'role')},
            },
        ),
    ]
