# Generated by Django 5.2.4 on 2025-07-26 19:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='end_time_seconds',
            field=models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='clip',
            name='start_time_seconds',
            field=models.DecimalField(decimal_places=3, max_digits=20, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
