# Generated by Django 5.2.4 on 2025-07-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_alter_clip_end_time_seconds_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='identification_confidence',
            field=models.CharField(blank=True, choices=[('certain', 'Certain'), ('probable', 'Probable'), ('possible', 'Possible'), ('uncertain', 'Uncertain')], default='uncertain', help_text='How confident are we in the identification?', max_length=20),
        ),
    ]
