# Generated by Django 5.2.4 on 2025-07-26 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0003_alter_clip_identification_confidence'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerformanceCast',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='performers',
        ),
    ]