# Generated by Django 5.2.4 on 2025-07-26 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_remove_performancecast_remove_old_performers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClipPerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.CharField(blank=True, help_text='Role, character, or performance notes for this clip', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_performers', to='archive.clip')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clip_performances', to='archive.person')),
            ],
            options={
                'ordering': ['clip', 'person__name'],
                'unique_together': {('clip', 'person')},
            },
        ),
        migrations.AddField(
            model_name='clip',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='clips', through='archive.ClipPerformer', to='archive.person'),
        ),
    ]