# Generated by Django 5.2.4 on 2025-07-26 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0005_clipperformer_clip_performers'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='clip',
            name='act_scene',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='archival_notes',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='audio_quality',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='camera_angle',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='clip_roles',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='costume_notes',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='identification_confidence',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='movement_tags',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='music_notes',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='music_section',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='technical_notes',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='video_quality',
        ),
        migrations.RemoveField(
            model_name='company',
            name='company_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
        migrations.RemoveField(
            model_name='company',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='company',
            name='website',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='is_gala',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='is_matinee',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='is_premiere',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='performance_time',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='program_notes',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='season',
        ),
        migrations.RemoveField(
            model_name='person',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='person',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='person',
            name='role',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='acts',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='approximate_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='description',
        ),
        migrations.RemoveField(
            model_name='piece',
            name='style',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='address',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='capacity',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='description',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='founded_year',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='venue_type',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='website',
        ),
        migrations.RemoveField(
            model_name='video',
            name='acquisition_notes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='digitization_notes',
        ),
        migrations.RemoveField(
            model_name='video',
            name='donor_contact',
        ),
        migrations.RemoveField(
            model_name='video',
            name='estimated_date_range',
        ),
        migrations.RemoveField(
            model_name='video',
            name='recording_quality',
        ),
        migrations.RemoveField(
            model_name='video',
            name='source_condition',
        ),
        migrations.RemoveField(
            model_name='video',
            name='source_format',
        ),
        migrations.RemoveField(
            model_name='video',
            name='source_location',
        ),
        migrations.AddField(
            model_name='video',
            name='provenance',
            field=models.TextField(blank=True, help_text='Chain of custody and acquisition history'),
        ),
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entity_types', models.JSONField(help_text="List of model names this field applies to: ['venue', 'piece', 'person', 'performance', 'video', 'clip']")),
                ('choices', models.JSONField(blank=True, help_text='For choice fields: list of options', null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('help_text', models.CharField(blank=True, max_length=200)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='archive.fieldtype')),
            ],
            options={
                'ordering': ['display_order', 'name'],
                'unique_together': {('name', 'field_type')},
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=255)),
                ('value', models.JSONField(help_text='Flexible storage for any field type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='archive.customfield')),
            ],
            options={
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='archive_cus_content_f8a8e8_idx'), models.Index(fields=['field'], name='archive_cus_field_i_168c3d_idx')],
                'unique_together': {('field', 'content_type', 'object_id')},
            },
        ),
    ]
