# Generated by Django 5.2.4 on 2025-10-13 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0006_fieldtype_alter_performance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original file name', max_length=255),
        ),
        migrations.AddField(
            model_name='video',
            name='tus_upload_url',
            field=models.URLField(blank=True, help_text='Cloudflare TUS upload URL for resumable uploads'),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_offset',
            field=models.BigIntegerField(default=0, help_text='Bytes uploaded so far'),
        ),
        migrations.AddField(
            model_name='video',
            name='upload_total',
            field=models.BigIntegerField(blank=True, help_text='Total file size in bytes', null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='cloudflare_playback_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='cloudflare_stream_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('error', 'Error')], default='pending', max_length=20),
        ),
    ]
