# Generated by Django 5.2.4 on 2025-12-07 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0007_video_original_filename_video_tus_upload_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformancePerformer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text="Character or role name (e.g., 'Giselle', 'Albrecht', 'Corps de ballet')", max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_performers', to='archive.performance')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_roles', to='archive.person')),
            ],
            options={
                'ordering': ['performance', 'person__name'],
                'unique_together': {('performance', 'person', 'role')},
            },
        ),
        migrations.AddField(
            model_name='performance',
            name='performers',
            field=models.ManyToManyField(blank=True, related_name='performances', through='archive.PerformancePerformer', to='archive.person'),
        ),
    ]
