# Generated by Django 5.2.4 on 2026-02-15 04:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0008_performanceperformer_performance_performers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='choices',
            field=models.JSONField(blank=True, help_text='For choice/dropdown fields, list the options like: ["Ballet", "Modern", "Duncan"]. Leave blank for text fields.', null=True),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='display_order',
            field=models.PositiveIntegerField(default=0, help_text='Fields with lower numbers appear first. Use 0, 10, 20 to leave room for future fields.'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='entity_types',
            field=models.JSONField(help_text='Which types of items should have this field'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='field_type',
            field=models.ForeignKey(help_text='What kind of field is this? Use "choice" for dropdowns with fixed options, "text" for free-form input.', on_delete=django.db.models.deletion.CASCADE, to='archive.fieldtype'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='help_text',
            field=models.CharField(blank=True, help_text='Optional hint shown to users when filling in this field', max_length=200),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='is_required',
            field=models.BooleanField(default=False, help_text='If checked, this field must be filled in whenever it appears'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(help_text='The name for this field, e.g. "Genre" or "Era"', max_length=100),
        ),
    ]
