# Generated by Django 5.2.4 on 2026-02-15 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0009_alter_customfield_choices_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='piece',
            options={'ordering': ['title'], 'verbose_name': 'Dance Work', 'verbose_name_plural': 'Dance Works'},
        ),
        migrations.AddField(
            model_name='clip',
            name='is_extracted',
            field=models.BooleanField(default=False, help_text='True once a real MP4 has been extracted to R2'),
        ),
        migrations.AddField(
            model_name='clip',
            name='r2_key',
            field=models.CharField(blank=True, help_text='R2 key for extracted clip MP4', max_length=500),
        ),
        migrations.AddField(
            model_name='clip',
            name='r2_thumbnail_key',
            field=models.CharField(blank=True, help_text='R2 key for clip thumbnail', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='r2_key',
            field=models.CharField(blank=True, help_text='R2 object key for original upload', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='r2_thumbnail_key',
            field=models.CharField(blank=True, help_text='R2 key for thumbnail image', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='r2_web_key',
            field=models.CharField(blank=True, help_text='R2 key for web-optimized transcode', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='duration_seconds',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
