# Generated by Django 5.2.4 on 2026-02-22 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0010_choreographer_to_m2m'),
        ('archive', '0010_r2_ffmpeg_fields'),
    ]

    operations = [
    ]
