# Generated by Django 5.2.4 on 2026-02-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0011_merge_0010_choreographer_to_m2m_0010_r2_ffmpeg_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='processing_error',
            field=models.TextField(blank=True, help_text='Error details if processing failed'),
        ),
        migrations.AddField(
            model_name='video',
            name='r2_upload_id',
            field=models.CharField(blank=True, help_text='S3 multipart upload ID for resumable R2 uploads', max_length=500),
        ),
        migrations.AddField(
            model_name='video',
            name='r2_upload_parts',
            field=models.JSONField(blank=True, help_text='Completed part ETags for multipart resume', null=True),
        ),
    ]
